syntax = "proto3";

package user.v1;

option go_package = "github.com/mathalama/nektokz/proto/user/v1";

import "google/protobuf/timestamp.proto";

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc IsBanned(IsBannedRequest) returns (IsBannedResponse);
  rpc UpdateProfile(UpdateProfileRequest) returns (UpdateProfileResponse);
}

message GetUserRequest {
  string user_id = 1;
}

message GetUserResponse {
  string id = 1;
  string gender = 3;
  bool is_banned = 4;
}

message IsBannedRequest {
  string user_id = 1;
}

message IsBannedResponse {
  bool banned = 1;
}

message UpdateProfileRequest {
  string user_id = 1;
  string gender = 2;
  repeated string interests = 3;
}

message UpdateProfileResponse {
  bool success = 1;
}

message AuthResponse {
  string access_token = 1;
  string refresh_token = 2;
}
