apiVersion: v1
kind: ConfigMap
metadata:
  name: sumdyk-config
  namespace: sumdyk
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  USER_SERVICE_URL: "http://user-service:8081"
  MATCHMAKING_SERVICE_URL: "http://matchmaking-service:8082"
  CHAT_SERVICE_URL: "http://chat-service:8083"
  MODERATION_SERVICE_URL: "http://moderation-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
  NATS_URL: "nats://host.minikube.internal:4222"
