apiVersion: v1
kind: Secret
metadata:
  name: sumdyk-secrets
  namespace: sumdyk
type: Opaque
stringData:
  JWT_SECRET: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
  INTERNAL_TOKEN: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
  USER_DB_URL: "postgres://<user>:<password>@<host>:5432/users_db?sslmode=disable"
  CHAT_DB_URL: "postgres://<user>:<password>@<host>:5432/chat_db?sslmode=disable"
  MODERATION_DB_URL: "postgres://<user>:<password>@<host>:5432/moderation_db?sslmode=disable"
  REDIS_URL: "redis://:<password>@<host>:6379"
