apiVersion: v1
kind: Secret
metadata:
  name: sumdyk-secrets
  namespace: sumdyk
type: Opaque
stringData:
  JWT_SECRET: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
  INTERNAL_TOKEN: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
  POSTGRES_PASSWORD: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
  REDIS_PASSWORD: "PLACEHOLDER_CHANGE_ME_IN_PRODUCTION"
