// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Get gateway health status",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/anonymous": {
            "post": {
                "description": "Create an anonymous user session",
                "tags": ["users"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "device_id": { "type": "string" }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tokens",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": { "type": "string" },
                                "refresh_token": { "type": "string" }
                            }
                        }
                    }
                }
            }
        },
        "/match/search": {
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Search for a partner",
                "tags": ["matchmaking"],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "filter": {
                                    "type": "object",
                                    "properties": {
                                        "gender": { "type": "string" },
                                        "interests": { "type": "array", "items": { "type": "string" } }
                                    }
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "202": { "description": "Accepted" }
                }
            }
        },
        "/match/status": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get current matchmaking status",
                "tags": ["matchmaking"],
                "responses": {
                    "200": { "description": "Status" }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get current user profile",
                "tags": ["users"],
                "responses": {
                    "200": { "description": "Profile" }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "NektoKZ API Gateway",
	Description:      "API Gateway for NektoKZ microservices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
