// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: matchmaking/v1/matchmaking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Interests     []string               `protobuf:"bytes,4,rep,name=interests,proto3" json:"interests,omitempty"`
	RoomTopic     string                 `protobuf:"bytes,5,opt,name=room_topic,json=roomTopic,proto3" json:"room_topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SearchRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *SearchRequest) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *SearchRequest) GetRoomTopic() string {
	if x != nil {
		return x.RoomTopic
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{3}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PartnerId     string                 `protobuf:"bytes,2,opt,name=partner_id,json=partnerId,proto3" json:"partner_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "searching", "matched", "idle"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_v1_matchmaking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_v1_matchmaking_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetStatusResponse) GetPartnerId() string {
	if x != nil {
		return x.PartnerId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_matchmaking_v1_matchmaking_proto protoreflect.FileDescriptor

const file_matchmaking_v1_matchmaking_proto_rawDesc = "" +
	"\n" +
	" matchmaking/v1/matchmaking.proto\x12\x0ematchmaking.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\rSearchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x1c\n" +
	"\tinterests\x18\x04 \x03(\tR\tinterests\x12\x1d\n" +
	"\n" +
	"room_topic\x18\x05 \x01(\tR\troomTopic\"*\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\rCancelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10GetStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"c\n" +
	"\x11GetStatusResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1d\n" +
	"\n" +
	"partner_id\x18\x02 \x01(\tR\tpartnerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xf8\x01\n" +
	"\x12MatchmakingService\x12G\n" +
	"\x06Search\x12\x1d.matchmaking.v1.SearchRequest\x1a\x1e.matchmaking.v1.SearchResponse\x12G\n" +
	"\x06Cancel\x12\x1d.matchmaking.v1.CancelRequest\x1a\x1e.matchmaking.v1.CancelResponse\x12P\n" +
	"\tGetStatus\x12 .matchmaking.v1.GetStatusRequest\x1a!.matchmaking.v1.GetStatusResponseB3Z1github.com/mathalama/nektokz/proto/matchmaking/v1b\x06proto3"

var (
	file_matchmaking_v1_matchmaking_proto_rawDescOnce sync.Once
	file_matchmaking_v1_matchmaking_proto_rawDescData []byte
)

func file_matchmaking_v1_matchmaking_proto_rawDescGZIP() []byte {
	file_matchmaking_v1_matchmaking_proto_rawDescOnce.Do(func() {
		file_matchmaking_v1_matchmaking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)))
	})
	return file_matchmaking_v1_matchmaking_proto_rawDescData
}

var file_matchmaking_v1_matchmaking_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_matchmaking_v1_matchmaking_proto_goTypes = []any{
	(*SearchRequest)(nil),     // 0: matchmaking.v1.SearchRequest
	(*SearchResponse)(nil),    // 1: matchmaking.v1.SearchResponse
	(*CancelRequest)(nil),     // 2: matchmaking.v1.CancelRequest
	(*CancelResponse)(nil),    // 3: matchmaking.v1.CancelResponse
	(*GetStatusRequest)(nil),  // 4: matchmaking.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 5: matchmaking.v1.GetStatusResponse
}
var file_matchmaking_v1_matchmaking_proto_depIdxs = []int32{
	0, // 0: matchmaking.v1.MatchmakingService.Search:input_type -> matchmaking.v1.SearchRequest
	2, // 1: matchmaking.v1.MatchmakingService.Cancel:input_type -> matchmaking.v1.CancelRequest
	4, // 2: matchmaking.v1.MatchmakingService.GetStatus:input_type -> matchmaking.v1.GetStatusRequest
	1, // 3: matchmaking.v1.MatchmakingService.Search:output_type -> matchmaking.v1.SearchResponse
	3, // 4: matchmaking.v1.MatchmakingService.Cancel:output_type -> matchmaking.v1.CancelResponse
	5, // 5: matchmaking.v1.MatchmakingService.GetStatus:output_type -> matchmaking.v1.GetStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matchmaking_v1_matchmaking_proto_init() }
func file_matchmaking_v1_matchmaking_proto_init() {
	if File_matchmaking_v1_matchmaking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaking_v1_matchmaking_proto_rawDesc), len(file_matchmaking_v1_matchmaking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaking_v1_matchmaking_proto_goTypes,
		DependencyIndexes: file_matchmaking_v1_matchmaking_proto_depIdxs,
		MessageInfos:      file_matchmaking_v1_matchmaking_proto_msgTypes,
	}.Build()
	File_matchmaking_v1_matchmaking_proto = out.File
	file_matchmaking_v1_matchmaking_proto_goTypes = nil
	file_matchmaking_v1_matchmaking_proto_depIdxs = nil
}
