syntax = "proto3";

package matchmaking.v1;

option go_package = "github.com/mathalama/nektokz/proto/matchmaking/v1";

import "google/protobuf/timestamp.proto";

service MatchmakingService {
  rpc Search(SearchRequest) returns (SearchResponse);
  rpc Cancel(CancelRequest) returns (CancelResponse);
  rpc GetStatus(GetStatusRequest) returns (GetStatusResponse);
}

message SearchRequest {
  string user_id = 1;
  string mode = 2;
  string gender = 3;
  repeated string interests = 4;
  string room_topic = 5;
}

message SearchResponse {
  bool success = 1;
}

message CancelRequest {
  string user_id = 1;
}

message CancelResponse {
  bool success = 1;
}

message GetStatusRequest {
  string user_id = 1;
}

message GetStatusResponse {
  string room_id = 1;
  string partner_id = 2;
  string status = 3; // "searching", "matched", "idle"
}
