name: Deploy API Gateway

on:
  push:
    branches: ["prod"]
    paths:
      - "services/api-gateway/**"
      - "infrastructure/docker/docker-compose.services.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_folder: "api-gateway"
      image_name: "api-gateway"
      compose_service: "api-gateway"
      env_image_var: "API_GATEWAY_IMAGE"
    secrets: inherit
