name: Deploy User Service

on:
  push:
    branches: ["prod"]
    paths:
      - "services/user-service/**"
      - "infrastructure/k8s/user-service.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-user-service
  cancel-in-progress: true

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-k8s-template.yml
    with:
      service_name: "user-service"
      build_context: "."
      dockerfile: "services/user-service/Dockerfile"
      manifest_path: "infrastructure/k8s/user-service.yaml"
      deployment_name: "user-service"
      namespace: "sumdyk"
    secrets: inherit
