name: Deploy Notification Service

on:
  push:
    branches: ["prod"]
    paths:
      - "services/notification-service/**"
      - "infrastructure/docker/docker-compose.services.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_folder: "notification-service"
      image_name: "notification-service"
      compose_service: "notification-service"
      env_image_var: "NOTIFICATION_SERVICE_IMAGE"
    secrets: inherit
