name: Deploy User Service

on:
  push:
    branches: ["dev"]
    paths:
      - "user-service/**"
      - "docker-compose.services.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_folder: "user-service"
      image_name: "user-service"
      compose_service: "user-service"
      env_image_var: "USER_SERVICE_IMAGE"
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}