name: Deploy Moderation Service

on:
  push:
    branches: ["prod"]
    paths:
      - "services/moderation-service/**"
      - "infrastructure/docker/docker-compose.services.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_folder: "moderation-service"
      image_name: "moderation-service"
      compose_service: "moderation-service"
      env_image_var: "MODERATION_SERVICE_IMAGE"
    secrets: inherit
