name: Deploy Matchmaking Service

on:
  push:
    branches: ["prod"]
    paths:
      - "services/matchmaking-service/**"
      - "infrastructure/k8s/matchmaking-service.yaml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-matchmaking-service
  cancel-in-progress: true

jobs:
  run-deploy:
    uses: ./.github/workflows/deploy-k8s-template.yml
    with:
      service_name: "matchmaking-service"
      build_context: "."
      dockerfile: "services/matchmaking-service/Dockerfile"
      manifest_path: "infrastructure/k8s/matchmaking-service.yaml"
      deployment_name: "matchmaking-service"
      namespace: "sumdyk"
    secrets: inherit
